name: Build and Push Docker Image

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Start Docker Service (if not running)
        run: |
          sudo systemctl start docker || echo "Docker already running"
          sudo systemctl status docker

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build -t spritegenix/cyber-sec-backend:latest .
          docker push spritegenix/cyber-sec-backend:latest

  deploy:
    needs: build
    runs-on: [ip-172-31-13-35]
    steps:
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Pull and Run Docker Image
        run: docker pull mydockerhubuser/myapp:latest

      - name: Delete Old Container (if exists)
        run: docker rm -f myapp-container || true

      - name: Run docker container
        run: docker run -d -p 4000:4000 --name myapp-container ghcr.io/spritegenix/cyber-sec-backend:latest
